# Setup

In [1]:
import tensorflow as tf
import numpy as np

In [10]:
# No GPU available
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [2]:
tf.__version__

'2.4.1'

# Constants

In [3]:
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [4]:
tensor_20.shape

TensorShape([2, 2])

In [5]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [21]:
# Note numpy arrays don't normally have an explicit dtype
numpy_tensor = np.array([[23,  4], [32, 51]])
numpy_tensor

array([[23,  4],
       [32, 51]])

In [27]:
# In fact, types can be mixed and matched
example_np = [1, 2.,]
example_np
# (if you convert this to a tensor, all values will be converted to floats
# ... and the overall tensor given a dtype of float32).

[1, 2.0]

In [28]:
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

# Variables

In [18]:
# Note the dtypes here - even if only a single float, goes to float32
# If all ints, goes to int32
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [29]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
tf2_variable[0, 2].assign(100)
# Note this has converted to a float to match dtype

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# Operations

In [31]:
op_tensor = tf.constant([[1, 2], [3, 4]])

In [33]:
op_tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [34]:
# Note original (constant) tensor not modified
op_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [35]:
op_tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [ ]:
# Numpy functional can be used: sqrt, square etc
# This converts to a numpy array, would need to be convered back to tensor

In [36]:
np.square(op_tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [38]:
# Linear algebra via
result = np.dot(op_tensor, tensor_20)
result

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [39]:
type(result)

numpy.ndarray

# Strings

In [40]:
tf_string = tf.constant("Tensorflow")

In [41]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [42]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [43]:
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [44]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
